const { REACT_APP_POLLING_INTERVAL, REACT_APP_SHOW_NEXT_INTERVAL } = process.env;
export const POLLING_INTERVAL = +(REACT_APP_POLLING_INTERVAL || 1000);
export const SHOW_NEXT_INTERVAL = +(REACT_APP_SHOW_NEXT_INTERVAL || 5000);
